services:
  customer-app:
    build: ./microservice-customers
    container_name: customer-app-container
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-customers:5432/customers-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - ms-network
    depends_on:
      db-customers:
        condition: service_healthy

  account-app:
    build: ./account-service
    container_name: account-app-container
    ports:
      - "8082:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-accounts:5432/accounts-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      # COMUNICACIÃ“N INTERNA: Usamos el nombre del servicio y el puerto interno
      - URL_CUSTOMER_SERVICE=http://customer-app:8080/api/v1/customers/
    networks:
      - ms-network
    depends_on:
      db-accounts:
        condition: service_healthy

  db-customers:
    image: postgres:15-alpine
    container_name: db-customers
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=customers-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customers-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ms-network

  db-accounts:
    image: postgres:15-alpine
    container_name: db-accounts
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=accounts-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d accounts-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge