services:
  app:
    build: .
    container_name: customer-app-container
    ports:
      - "8081:8080"
    environment:
      
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customers-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - ms-network  # Misma red que el db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: db-customers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: customers-db
    ports:
      - "5432:5432"
    networks:
      - ms-network
    volumes:
      - postgres-s-data:/var/lib/postgresql
    healthcheck:
      # Usuario y DB corregidos para coincidir con environment
      test: ["CMD-SHELL", "pg_isready -U postgres -d customers-db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ms-network: # Unificamos el nombre de la red
    driver: bridge

volumes:
  postgres-s-data: